### ISSUE TITLE
Does the library support python 3?

### ISSUE THREAD

**Issue by chenshuiluke** [nathancahill/flask-inputs#9]
When I try to use it, I get the following error:

    File "/home/luke/Documents/code/git/notebook/venv/lib/python3.6/site-packages/flask_inputs/inputs.py", line 34, in __init__
    for field, validators in input.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'

AFAIK dict.iteritems isn't available in Python 3

**Comment by alx-k** [comment]
Doesn't appear to work with 3.6

**Comment by alx-k** [comment]
Latest version on PyPi doesn't have the python3  fix: https://pypi.python.org/pypi/Flask-Inputs/0.2.0
Anyway this can be updated?

**Comment by RenanOliv** [comment]
@alx-k In the meantime, you can use `pip install` to add [packages from github](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support) using the `git+` prefix.
To be able to freeze it in your requirements you can also add the `--edible` option:

```shell
pip install -e https://github.com/nathancahill/flask-inputs.git#egg=Flask-Inputs
```

**Comment by cblegare** [comment]
Hi!, Is there anything we can do to help updating the PyPI package?

**Comment by adekoder** [comment]
how do i help updating this in pypi instead of have to clone the repo before i can get it to work with python 3.6

**Comment by colinben** [comment]
Hi, is there any chance you could upload to PyPI? Thanks

**Comment by joyider** [comment]
Will the working version be updated to PyPi?

**Comment by alexlouden** [comment]
@nathancahill could you please make a new release? It'd be great to get Python 3 fixes into pypi. Thanks!

**Comment by nathancahill** [comment]
Hi, this is now uploaded to PyPI as 0.3. Would anyone in this thread be interested in helping to maintain this library?

**Comment by kaangoksal** [comment]
I would be interested in maintaining this library, I'm actively working on it right now
